# Importing Relevant Libraries

In [578]:
import pandas as pd
import numpy as np

# Load the Data

In [579]:
raw_csv_data = pd.read_csv("Absenteeism_data.csv")

# Data Processing

In [580]:
#creating a copy of the data to ensure data integrity and prevent any loss or corruption
df = raw_csv_data.copy()
df.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

In [581]:
df.describe()

ID  Reason for Absence  Transportation Expense  \
count  700.000000          700.000000              700.000000   
mean    17.951429           19.411429              222.347143   
std     11.028144            8.356292               66.312960   
min      1.000000            0.000000              118.000000   
25%      9.000000           13.000000              179.000000   
50%     18.000000           23.000000              225.000000   
75%     28.000000           27.000000              260.000000   
max     36.000000           28.000000              388.000000   

       Distance to Work         Age  Daily Work Load Average  Body Mass Index  \
count        700.000000  700.000000               700.000000       700.000000   
mean          29.892857   36.417143               271.801774        26.737143   
std           14.804446    6.379083                40.021804         4.254701   
min            5.000000   27.000000               205.917000        19.000000   
25%           16.000000   31.000000               241.476000        24.000000   
50%           26.000000   37.000000               264.249000        25.000000   
75%           50.000000   40.000000               294.217000        31.000000   
max           52.000000   58.000000               378.884000        38.000000   

        Education    Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000  700.000000                 700.000000  
mean     1.282857    1.021429    0.687143                   6.761429  
std      0.668090    1.112215    1.166095                  12.670082  
min      1.000000    0.000000    0.000000                   0.000000  
25%      1.000000    0.000000    0.000000                   2.000000  
50%      1.000000    1.000000    0.000000                   3.000000  
75%      1.000000    2.000000    1.000000                   8.000000  
max      4.000000    4.000000    8.000000                 120.000000

In [582]:
#dropping the ID column
df = df.drop(['ID'], axis = 1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [583]:
reason_columns = pd.get_dummies(df['Reason for Absence'])

reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns = reason_columns.drop(['check'], axis = 1)


reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)


In [584]:
#dropping the column 'Reason for Absence'
df = df.drop(['Reason for Absence'], axis = 1)
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [585]:
#replacing the 'Reason for Absence' column with 4 columns 
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)

In [586]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

df.columns = column_names

In [587]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

df = df[column_names_reordered]

df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [588]:
df['Date'] = pd.to_datetime(df['Date'], format = '%d/%m/%Y')

In [589]:
list_months = []

In [590]:
for i in range(df.shape[0]):
    list_months.append(df['Date'][i].month)
    
# list_months
# len(list_months)
df['Month Value'] = list_months
# df_reason_mod.head(20)


In [591]:
def date_to_weekday(date_value):
    return date_value.weekday()

df['Day of the Week'] = df['Date'].apply(date_to_weekday)

In [592]:
df = df.drop(['Date'], axis = 1)
# df_reason_mod.head()
# df_reason_mod.columns.values
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

df.head()


Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [593]:
#Converting the values in the education column into binary
df['Education'] = df['Education'].map({1:0, 2:1, 3:1, 4:1})

In [594]:
data_preprocessed = df.copy()
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  Month Value  \
0            0         2     1                          4            7   
1            0         1     0                          0            7   
2            0         0     0                          2            7   
3            0         2     0                          4            7   
4            0         2     1                          2            7   
..         ...       ...   ...                        ...          ...   
695          1         2     0                          8            5   
696          0         1     2                          3            5   
697          1         0     0                          8            5   
698          1         0     0                          2            5   
699          0         1     1                          2            5   

     Day of the Week  
0                  1  
1                  1  
2                  2  
3                  3  
4                  3  
..               ...  
695                2  
696                2  
697                3  
698                3  
699                3  

[700 rows x 15 columns]

# Create the targets

In [595]:
data_preprocessed['Absenteeism Time in Hours'].median()
#Here we are using median instead of mean beacause the median is resistant to extreme values or outliers

3.0

In [596]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [597]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [598]:
# create a Series in the original data frame that will contain the targets for the regression analysis
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# Target Analysis

In [599]:
# check if dataset is balanced (what % of targets are 1s)
targets.sum() / targets.shape[0]

0.45571428571428574

In [600]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours',],axis=1)

#Here we can drop columns such as 'Day of the Week','Daily Work Load Average','Distance to Work' also
#after initially testing we will find that these factors have very affect in determining absenteeism
#removing these columns will increase the accuracy by a few percentages

In [601]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  Day of the Week  Excessive Absenteeism  
0         2     1            7                1                      1  
1         1     0            7                1                      0  
2         0     0            7                2                      0  
3         2     0            7                3                      1  
4         2     1            7                3                      0

# Selecting inputs for regression

In [602]:
data_with_targets.shape

(700, 15)

In [603]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  Day of the Week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [604]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  Day of the Week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [605]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
#this variable will contain the inputs(everything except the target variable)

# Standardize the Data

In [606]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [607]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [608]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [609]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [610]:
scaled_inputs.shape

(700, 14)

#   Split the data into train data and test data

In [611]:
from sklearn.model_selection import train_test_split

In [612]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.18272635, -0.68370352],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.18272635,  0.66825259],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.61027597,  0.66825259],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.03925612,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.61027597,  1.34423065],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.95931334, -1.35968157]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -1.24482327, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.12666297,
         -0.10278357, -1.35968157],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
          1.61027597, -0.68370352],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [613]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.75, 
                                                                            test_size = 0.25, random_state = 20)

In [614]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

(525, 14) (525,)
(175, 14) (175,)


# Logistic regression with sklearn

In [615]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [616]:
reg = LogisticRegression()

In [617]:
reg.fit(x_train,y_train)

LogisticRegression()

In [618]:
#this will asses the training accuracy of the model
reg.score(x_train,y_train)

0.7828571428571428

# Manually checking the accuracy

In [619]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,

In [620]:
y_train

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [621]:
model_outputs == y_train

array([ True, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
        True,  True,

In [622]:
np.sum((model_outputs==y_train))

411

In [623]:
model_outputs.shape[0]

525

In [624]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7828571428571428

# Finding the intercept and coefficients

In [625]:
#get the intercept of our model
reg.intercept_

array([-0.211116])

In [626]:
#get the coefficients of our model
reg.coef_

array([[ 2.07111332,  0.34545968,  1.55786681,  1.28301993,  0.74811703,
        -0.02156145, -0.20541518, -0.00337051,  0.37570735, -0.19598516,
         0.32508287, -0.34476035,  0.21500264, -0.11946966]])

In [627]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [628]:
feature_name = unscaled_inputs.columns.values

In [629]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.071113
1                  Reason_2     0.345460
2                  Reason_3     1.557867
3                  Reason_4     1.283020
4    Transportation Expense     0.748117
5          Distance to Work    -0.021561
6                       Age    -0.205415
7   Daily Work Load Average    -0.003371
8           Body Mass Index     0.375707
9                 Education    -0.195985
10                 Children     0.325083
11                     Pets    -0.344760
12              Month Value     0.215003
13          Day of the Week    -0.119470

In [630]:
#move the intercept to the top of the summary table
summary_table.index = summary_table.index + 1

summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.211116
1                  Reason_1     2.071113
2                  Reason_2     0.345460
3                  Reason_3     1.557867
4                  Reason_4     1.283020
5    Transportation Expense     0.748117
6          Distance to Work    -0.021561
7                       Age    -0.205415
8   Daily Work Load Average    -0.003371
9           Body Mass Index     0.375707
10                Education    -0.195985
11                 Children     0.325083
12                     Pets    -0.344760
13              Month Value     0.215003
14          Day of the Week    -0.119470

# Interpreting the coefficients

In [631]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [632]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.211116    0.809680
1                  Reason_1     2.071113    7.933651
2                  Reason_2     0.345460    1.412639
3                  Reason_3     1.557867    4.748681
4                  Reason_4     1.283020    3.607518
5    Transportation Expense     0.748117    2.113018
6          Distance to Work    -0.021561    0.978669
7                       Age    -0.205415    0.814309
8   Daily Work Load Average    -0.003371    0.996635
9           Body Mass Index     0.375707    1.456021
10                Education    -0.195985    0.822024
11                 Children     0.325083    1.384145
12                     Pets    -0.344760    0.708390
13              Month Value     0.215003    1.239865
14          Day of the Week    -0.119470    0.887391

In [633]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.071113    7.933651
3                  Reason_3     1.557867    4.748681
4                  Reason_4     1.283020    3.607518
5    Transportation Expense     0.748117    2.113018
9           Body Mass Index     0.375707    1.456021
2                  Reason_2     0.345460    1.412639
11                 Children     0.325083    1.384145
13              Month Value     0.215003    1.239865
8   Daily Work Load Average    -0.003371    0.996635
6          Distance to Work    -0.021561    0.978669
14          Day of the Week    -0.119470    0.887391
10                Education    -0.195985    0.822024
7                       Age    -0.205415    0.814309
0                 Intercept    -0.211116    0.809680
12                     Pets    -0.344760    0.708390

# Testing the model

In [634]:
reg.score(x_test,y_test)

0.7257142857142858

In [635]:
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

predicted_proba

array([[0.72165646, 0.27834354],
       [0.59436996, 0.40563004],
       [0.31080044, 0.68919956],
       [0.80843486, 0.19156514],
       [0.06077977, 0.93922023],
       [0.25916577, 0.74083423],
       [0.30549908, 0.69450092],
       [0.07494542, 0.92505458],
       [0.82185518, 0.17814482],
       [0.73774401, 0.26225599],
       [0.42593539, 0.57406461],
       [0.153094  , 0.846906  ],
       [0.05295652, 0.94704348],
       [0.75051342, 0.24948658],
       [0.24479016, 0.75520984],
       [0.58841771, 0.41158229],
       [0.50179226, 0.49820774],
       [0.54964466, 0.45035534],
       [0.39508216, 0.60491784],
       [0.02007975, 0.97992025],
       [0.69723491, 0.30276509],
       [0.79561556, 0.20438444],
       [0.33751475, 0.66248525],
       [0.37452066, 0.62547934],
       [0.18419486, 0.81580514],
       [0.77344239, 0.22655761],
       [0.49601294, 0.50398706],
       [0.91422526, 0.08577474],
       [0.10742428, 0.89257572],
       [0.78216954, 0.21783046],
       [0.

In [636]:
predicted_proba.shape

(175, 2)

In [637]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.27834354, 0.40563004, 0.68919956, 0.19156514, 0.93922023,
       0.74083423, 0.69450092, 0.92505458, 0.17814482, 0.26225599,
       0.57406461, 0.846906  , 0.94704348, 0.24948658, 0.75520984,
       0.41158229, 0.49820774, 0.45035534, 0.60491784, 0.97992025,
       0.30276509, 0.20438444, 0.66248525, 0.62547934, 0.81580514,
       0.22655761, 0.50398706, 0.08577474, 0.89257572, 0.21783046,
       0.38667333, 0.71494956, 0.7463266 , 0.60363999, 0.20438444,
       0.52935866, 0.18787998, 0.81300621, 0.46193593, 0.5615886 ,
       0.23473477, 0.35117133, 0.19355482, 0.09191043, 0.87807477,
       0.68275983, 0.70231803, 0.29418962, 0.1898399 , 0.17216785,
       0.55617243, 0.09070146, 0.7229912 , 0.30112937, 0.89211851,
       0.51614545, 0.94490245, 0.22931258, 0.10106821, 0.09954197,
       0.72965428, 0.71189812, 0.29670295, 0.86718241, 0.16001211,
       0.28665883, 0.01382181, 0.21323112, 0.82320415, 0.29830057,
       0.18738751, 0.08487148, 0.95017584, 0.45746721, 0.67537

# Saving the model


In [638]:
import pickle

In [639]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [640]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)